version: '3'

services:

  node-a:
    container_name: node-a
    image: basic-paxos:latest
    hostname: node-a
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - pax-net
    ports:
      - 9846:2020
    labels:
      kompose.service.type: LoadBalancer

networks:
  pax-net:
    driver: bridge