version: '3'

services:

  paxos:
    container_name: paxos
    image: paxos:latest
    hostname: paxos
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./artifacts:/artifacts

  basic-paxos-mermaid:
    container_name: basic-paxos-mermaid
    image: minlag/mermaid-cli:latest
    hostname: mermaid
    command: ["-i", "/artifacts/basic-paxos-output.txt", "-o", "/artifacts/basic-paxos-output.pdf"]
    depends_on:
      - paxos
    volumes:
      - ./artifacts:/artifacts

  multi-paxos-mermaid:
    container_name: multi-paxos-mermaid
    image: minlag/mermaid-cli:latest
    hostname: mermaid
    command: [ "-i", "/artifacts/multi-paxos-output.txt", "-o", "/artifacts/multi-paxos-output.pdf" ]
    depends_on:
      - paxos
    volumes:
      - ./artifacts:/artifacts